# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 不可能不确定
subtitle: A Node.js Developer
description: 不可能不确定的博主是一名Node.js程序员，博客的内容会涉及电影 / 生活 / 吐槽 / JavaScript / PHP / Node.js / Express / MongoDB / MySQL / Redis / AngularJS / jQuery / HTML。
author: Stiekel
email: histkc@gmail.com
language: zh-CN

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://chensd.com
root: /
permalink: :year-:month/:title.html
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# Directory
source_dir: source
public_dir: public
skip_render: 
  - "books"
  - "books/*"
  - "books/**/*"
  - "code/*"
  - "code/**/*"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: true
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
highlight:
  enable: true
  line_number: true
  tab_replace: 2

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: 0.0.0.0
logger: false
logger_format: dev

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: ll
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Disqus
# disqus_shortname:

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: random
exclude_generator:

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    coding: git@git.coding.net:Stiekel/blog.git,coding-pages
    github: git@github.com:stiekel/stiekel.github.io.git,master
  #repository: https://gitcafe.com/Sid/Sid.git
  #repository: git@gitcafe.com:Sid/Sid.git
  #branch: gitcafe-pages
  # repository: https://git.coding.net/Stiekel/blog.git
  # branch: coding-pages
  # repository: https://github.com/stiekel/stiekel.github.io.git
  # boranch: master

duoshuo_shortname: sidcn
# uyan_id: 2066860

social:
  GitHub: https://github.com/stiekel
  Coding.NET: https://coding.net/u/Stiekel
  Twitter: https://twitter.com/SidCN
  Weibo: http://weibo.com/sidcn
  DouBan: http://www.douban.com/people/Stiekel/

menu:
  首页: index.html
  文章: archives
  标签: tags
  分类: categories
  关于: about

creative_commons: by-nc-sa
google_analytics: UA-3804589-6
baidu_analytics: 6ab46e09bc8d0da169baff9f975ecaf8
# jiaThis_uid: 2066860
since: 2010

feed:
  type: atom
  path: atom.xml
  limit: 30

archive_generator:
  per_page: 1000
  yearly: true
  monthly: false
